---
# install tasks file for ansible-role-unixodbc

- name: Install UnixODBC
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
    - unixodbc
  register: my_result
  until: my_result is succeeded
  tags: unixodbc
